Repository BTS-Busan-Trip-Supporter/back-end, pull requests merged in 2024-08, with the labels that each got.

#8 Feat/basic security chain
  .gitignore
  build.gradle
  src/main/java/org/bts/backend/auth_filter/AuthenticationFilter.java
  src/main/java/org/bts/backend/auth_filter/AuthorizationFilter.java
  src/main/java/org/bts/backend/config/AppConfig.java
  src/main/java/org/bts/backend/config/MailConfig.java
  src/main/java/org/bts/backend/config/RedisConfig.java
  src/main/java/org/bts/backend/config/SecurityConfig.java
  src/main/java/org/bts/backend/controller/MemberController.java
  src/main/java/org/bts/backend/domain/Member.java
  src/main/java/org/bts/backend/domain/RefreshToken.java
  src/main/java/org/bts/backend/domain/constant/Role.java
  src/main/java/org/bts/backend/dto/OAuthAttributeDto.java
  src/main/java/org/bts/backend/dto/request/LoginRequest.java
  src/main/java/org/bts/backend/dto/request/MailCertRequest.java
  src/main/java/org/bts/backend/dto/response/JwtTokenResponse.java
  src/main/java/org/bts/backend/repository/MailCertRedisRepository.java
  src/main/java/org/bts/backend/repository/MemberRepository.java
  src/main/java/org/bts/backend/repository/RefreshTokenRedisRepository.java
  src/main/java/org/bts/backend/service/MemberService.java
  src/main/java/org/bts/backend/service/MemberServiceImpl.java
  src/main/java/org/bts/backend/service/TokenService.java
  src/main/java/org/bts/backend/service/TokenServiceImpl.java
  src/main/java/org/bts/backend/util/CookieProvider.java
  src/main/java/org/bts/backend/util/JwtTokenProvider.java
  src/main/java/org/bts/backend/util/MailProvider.java
  src/main/java/org/bts/backend/util/OauthUtil.java
  src/main/resources/application.yaml
Labels: ✨ Feature, 🥇 Urgency1

#12 Feat/swagger configuration
  build.gradle
  src/main/java/org/bts/backend/config/SwaggerConfig.java
  src/main/java/org/bts/backend/controller/MemberController.java
Labels: ✨ Feature, 📃 Docs, 🥈Urgency2

#15 Deploy/aws
  Dockerfile
Labels: 🌏 Deploy, 📃 Docs, ⚙ Setting

#16 Feat/#2 db
  src/main/java/org/bts/backend/domain/BaseTimeEntity.java
  src/main/java/org/bts/backend/domain/StartEndTimeEntity.java
  src/main/java/org/bts/backend/domain/TourActivity.java
  src/main/java/org/bts/backend/domain/TourDay.java
  src/main/java/org/bts/backend/domain/TourLog.java
  src/main/java/org/bts/backend/domain/TourSpot.java
  src/main/java/org/bts/backend/domain/TourSpotRating.java
Labels: ✨ Feature, 🛢️ DataBase

#17 Feat/error handler
  src/main/java/org/bts/backend/auth_filter/AuthenticationFilter.java
  src/main/java/org/bts/backend/config/SecurityConfig.java
  src/main/java/org/bts/backend/controller/MemberController.java
  src/main/java/org/bts/backend/exception/CustomException.java
  src/main/java/org/bts/backend/exception/FilterExceptionHandler.java
  src/main/java/org/bts/backend/exception/MVCGlobalException.java
  src/main/java/org/bts/backend/exception/after_servlet/MailException.java
  src/main/java/org/bts/backend/exception/after_servlet/NoCredException.java
  src/main/java/org/bts/backend/exception/after_servlet/UsernameNotFoundException.java
  src/main/java/org/bts/backend/exception/before_servlet/CustomAuthException.java
  src/main/java/org/bts/backend/exception/before_servlet/CustomIOException.java
  src/main/java/org/bts/backend/exception/before_servlet/CustomTokenException.java
  src/main/java/org/bts/backend/service/MemberServiceImpl.java
  src/main/java/org/bts/backend/service/TokenServiceImpl.java
  src/main/java/org/bts/backend/util/JwtTokenProvider.java
  src/main/java/org/bts/backend/util/MailProvider.java
  src/main/java/org/bts/backend/util/OauthUtil.java
Labels: ✨ Feature, 🥈Urgency2

#19 Feat/public trans api
  build.gradle
  src/main/java/org/bts/backend/api/tmap/TmapAPI.java
  src/main/java/org/bts/backend/api/tmap/TmapResponse.java
  src/main/java/org/bts/backend/controller/TestController.java
  src/main/java/org/bts/backend/domain/TourSpotRating.java
Labels: ✨ Feature, 🥇 Urgency1, 🌐 API
