Repository BTS-Busan-Trip-Supporter/back-end, pull requests merged in 2024-09, with the labels that each got.

#21 Feat/cicd
  .github/workflows/deploy.yml
  .gitignore
  docker-compose.yml
  src/main/resources/application-deploy.yml
Labels: 🌏 Deploy, ✨ Feature, 🥇 Urgency1

#22 Feat/day trip
  src/main/java/org/bts/backend/controller/APIController.java
  src/main/java/org/bts/backend/controller/TourSpotController.java
  src/main/java/org/bts/backend/controller/TripController.java
  src/main/java/org/bts/backend/domain/TourSpot.java
  src/main/java/org/bts/backend/domain/constant/ContentType.java
  src/main/java/org/bts/backend/domain/constant/DayTime.java
  src/main/java/org/bts/backend/dto/request/DayTripRequest.java
  src/main/java/org/bts/backend/dto/response/DayTripResponse.java
  src/main/java/org/bts/backend/dto/response/TourSpotDetailResponse.java
  src/main/java/org/bts/backend/dto/response/tourapi/AreaBasedResponse.java
  src/main/java/org/bts/backend/dto/response/tourapi/DetailCommonResponse.java
  src/main/java/org/bts/backend/dto/response/tourapi/DetailIntroResponse.java
  src/main/java/org/bts/backend/repository/TourSpotRepository.java
  src/main/java/org/bts/backend/service/DayTripService.java
  src/main/java/org/bts/backend/service/DayTripServiceImpl.java
  src/main/java/org/bts/backend/service/TourAPIService.java
  src/main/java/org/bts/backend/service/TourAPIServiceImpl.java
  src/main/java/org/bts/backend/service/TourSpotService.java
  src/main/java/org/bts/backend/service/TourSpotServiceImpl.java
  src/main/java/org/bts/backend/util/RegexUtil.java
Labels: ✨ Feature, 🌐 API, 🛢️ DataBase

#27 Bugfix/mail sender
  .github/workflows/deploy.yml
  docker-compose.yml
  src/main/java/org/bts/backend/config/RedisConfig.java
  src/main/java/org/bts/backend/util/MailProvider.java
  src/main/java/org/bts/backend/util/OauthUtil.java
  src/main/resources/application-deploy.yml
Labels: 🐞 BugFix, ⚙ Setting, 🌐 API

#32 Docs/swagger
  src/main/java/org/bts/backend/controller/TourSpotController.java
  src/main/java/org/bts/backend/controller/TripController.java
  src/main/java/org/bts/backend/dto/request/DayTripRequest.java
  src/main/java/org/bts/backend/dto/request/ScheduleTripRequest.java
  src/main/java/org/bts/backend/dto/request/ScheduleTripUpdateRequest.java
  src/main/java/org/bts/backend/dto/request/TourActivityHistoryRequest.java
  src/main/java/org/bts/backend/dto/response/DayTripResponse.java
Labels: 📃 Docs, 🌐 API

#33 fix: change logout logic
  src/main/java/org/bts/backend/auth_filter/AuthenticationFilter.java
  src/main/java/org/bts/backend/auth_filter/AuthorizationFilter.java
  src/main/java/org/bts/backend/config/SecurityConfig.java
  src/main/java/org/bts/backend/controller/MemberController.java
  src/main/java/org/bts/backend/util/JwtTokenProvider.java
  src/main/resources/application-deploy.yml
Labels: 🐞 BugFix, ✨ Feature, 🥇 Urgency1
